[images]
upper   = "docker.io/ericbottard/uppercase-node"
divider = "docker.io/ericbottard/divider-node"
counter = "docker.io/ericbottard/counter-node"
md5     = "docker.io/ericbottard/md5-node"
repeater = "docker.io/ericbottard/repeater-node"
